[package]
name = "wireguard2clash"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ipnetwork = "0.20.0"
serde_json = "1.0.113"
serde = { version = "1.0", features = ["derive"] }